version: '3.8'

services:
  micolita-addon:
    build: .
    container_name: micolita-stremio
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - RESOLVE_DIRECT_LINKS=true # Activa la resolución de enlaces directos usando Puppeteer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
